//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentScore
    {
        public System.Guid assessment_score_id { get; set; }
        public System.Guid entered_by { get; set; }
        public System.Guid assessment_id { get; set; }
        public System.Guid enrollment_id { get; set; }
        public decimal score { get; set; }
        public string feedback { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual User User { get; set; }
    }
}
