//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceRecord
    {
        public System.Guid attendance_id { get; set; }
        public System.Guid enrollment_id { get; set; }
        public System.Guid session_id { get; set; }
        public System.Guid recorded_by { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string attendance_status { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual ClassSession ClassSession { get; set; }
        public virtual User User { get; set; }
    }
}
