//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassSession()
        {
            this.AttendanceRecords = new HashSet<AttendanceRecord>();
        }
    
        public System.Guid session_id { get; set; }
        public System.Guid class_id { get; set; }
        public System.Guid time_slot_id { get; set; }
        public System.DateTime session_date { get; set; }
        public string topic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual Class Class { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
