//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchedule
    {
        public System.Guid class_schedule_id { get; set; }
        public System.Guid class_id { get; set; }
        public System.Guid time_slot_id { get; set; }
        public string room_name { get; set; }
        public string week_day { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }
}
