//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Enrollment()
        {
            this.AssessmentScores = new HashSet<AssessmentScore>();
            this.AttendanceRecords = new HashSet<AttendanceRecord>();
            this.Payments = new HashSet<Payment>();
        }
    
        public System.Guid enrollment_id { get; set; }
        public System.Guid class_id { get; set; }
        public System.Guid student_id { get; set; }
        public System.DateTime enrollment_date { get; set; }
        public string notes { get; set; }
        public decimal tuition_amount { get; set; }
        public Nullable<System.DateTime> confirmed_at { get; set; }
        public Nullable<System.DateTime> withdrawn_at { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string enrollment_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentScore> AssessmentScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceRecord> AttendanceRecords { get; set; }
        public virtual Class Class { get; set; }
        public virtual Student_Profile Student_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
