//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid notification_id { get; set; }
        public System.Guid user_id { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string notification_type { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string read_status { get; set; }
    
        public virtual User User { get; set; }
    }
}
