//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid payment_id { get; set; }
        public System.Guid recorded_by { get; set; }
        public System.Guid enrollment_id { get; set; }
        public decimal amount { get; set; }
        public System.DateTime payment_date { get; set; }
        public string receipt_number { get; set; }
        public string notes { get; set; }
        public System.DateTime created_at { get; set; }
        public string payment_status { get; set; }
        public string payment_method { get; set; }
    
        public virtual Enrollment Enrollment { get; set; }
        public virtual User User { get; set; }
    }
}
