//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyllabusMaterial
    {
        public System.Guid syllabus_id { get; set; }
        public System.Guid course_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string file_url { get; set; }
        public string available_status { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
