//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher_qualification
    {
        public System.Guid qualification_id { get; set; }
        public System.Guid teacher_id { get; set; }
        public string qualification_name { get; set; }
        public string institution { get; set; }
        public Nullable<System.DateTime> issued_date { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string available_status { get; set; }
    
        public virtual Teacher_profile Teacher_profile { get; set; }
    }
}
