//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AssessmentScores = new HashSet<AssessmentScore>();
            this.AttendanceRecords = new HashSet<AttendanceRecord>();
            this.Notifications = new HashSet<Notification>();
            this.Payments = new HashSet<Payment>();
            this.Staff_Profile = new HashSet<Staff_Profile>();
            this.Student_Profile = new HashSet<Student_Profile>();
            this.Roles = new HashSet<Role>();
        }
    
        public System.Guid user_id { get; set; }
        public string username { get; set; }
        public string hashed_password { get; set; }
        public string email { get; set; }
        public string auth_provider { get; set; }
        public string auth_provider_key { get; set; }
        public string full_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string phone_number { get; set; }
        public string gender { get; set; }
        public string avatar_url { get; set; }
        public string native_language { get; set; }
        public string emergency_contact_number { get; set; }
        public string emergency_contact_name { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string active_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentScore> AssessmentScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceRecord> AttendanceRecords { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Profile> Staff_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Profile> Student_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Roles { get; set; }
    }
}
